// Generated by scripts/sync-openapi-types.mjs. Do not edit by hand.
// OpenAPI version: 3.0.3

export type DemoCounts = { readonly "daily_bars": number; readonly "financial_metrics": number; readonly "instruments": number }

export type DemoSampleStock = { readonly "code": string; readonly "exchange": "SSE" | "SZSE"; readonly "name": string; readonly "status": "active" }

export type DemoStatus = { readonly "as_of": string; readonly "counts": DemoCounts; readonly "mode": "demo" | "real" | "fallback"; readonly "provider": "mysql-demo-fixture" | "external-real-provider" | "local-fixture-fallback"; readonly "sample_stocks": ReadonlyArray<DemoSampleStock>; readonly "seed_version": string }

export type ErrorResponse = { readonly "code": "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "VALIDATION_ERROR" | "INVALID_PAGINATION" | "INTERNAL_ERROR" | "DEPENDENCY_UNAVAILABLE"; readonly "details"?: { readonly [key: string]: unknown }; readonly "message": string }

export type HealthResponse = { readonly "status": string }

export type PaginatedResponse = { readonly "data": ReadonlyArray<unknown>; readonly "pagination": PaginationMeta }

export type PaginationMeta = { readonly "page": number; readonly "page_size": number; readonly "total": number; readonly "total_pages": number }

export type PaginationRequest = { readonly "page"?: number; readonly "page_size"?: number }

export type Response = { readonly "data": unknown }

export type ApiPaths = { readonly "/api/v1/dev/demo-status": { readonly get: { readonly responses: { readonly "200": { readonly content: { readonly "application/json": DemoStatus }}; readonly "404": { readonly content: { readonly "application/json": ErrorResponse }}; readonly "405": { readonly content: { readonly "application/json": ErrorResponse }}; readonly "503": { readonly content: { readonly "application/json": ErrorResponse }} } } }; readonly "/api/v1/health": { readonly get: { readonly responses: { readonly "200": { readonly content: { readonly "application/json": HealthResponse }}; readonly "404": { readonly content: { readonly "application/json": ErrorResponse }}; readonly "405": { readonly content: { readonly "application/json": ErrorResponse }}; readonly "500": { readonly content: { readonly "application/json": ErrorResponse }} } } }; readonly "/api/v1/openapi.json": { readonly get: { readonly responses: { readonly "200": { readonly content: { readonly "application/json": Record<string, never> }}; readonly "404": { readonly content: { readonly "application/json": ErrorResponse }}; readonly "405": { readonly content: { readonly "application/json": ErrorResponse }}; readonly "500": { readonly content: { readonly "application/json": ErrorResponse }} } } } }
