// Generated by scripts/sync-openapi-types.mjs. Do not edit by hand.
// OpenAPI version: 3.0.3

export type ErrorResponse = { readonly "code": "NOT_FOUND" | "METHOD_NOT_ALLOWED" | "VALIDATION_ERROR" | "INVALID_PAGINATION" | "INTERNAL_ERROR"; readonly "details"?: { readonly [key: string]: unknown }; readonly "message": string }

export type HealthResponse = { readonly "status": string }

export type PaginatedResponse = { readonly "data": ReadonlyArray<unknown>; readonly "pagination": PaginationMeta }

export type PaginationMeta = { readonly "page": number; readonly "page_size": number; readonly "total": number; readonly "total_pages": number }

export type PaginationRequest = { readonly "page"?: number; readonly "page_size"?: number }

export type Response = { readonly "data": unknown }

export type ApiPaths = { readonly "/api/v1/health": { readonly get: { readonly responses: { readonly "200": { readonly content: { readonly "application/json": HealthResponse }}; readonly "404": { readonly content: { readonly "application/json": ErrorResponse }}; readonly "405": { readonly content: { readonly "application/json": ErrorResponse }}; readonly "500": { readonly content: { readonly "application/json": ErrorResponse }} } } }; readonly "/api/v1/openapi.json": { readonly get: { readonly responses: { readonly "200": { readonly content: { readonly "application/json": Record<string, never> }}; readonly "404": { readonly content: { readonly "application/json": ErrorResponse }}; readonly "405": { readonly content: { readonly "application/json": ErrorResponse }}; readonly "500": { readonly content: { readonly "application/json": ErrorResponse }} } } } }
