// 本文件只转出由后端 OpenAPI 生成的 wire types，不维护第二份手写 DTO。
export type {
  ApiPaths,
  DemoCounts,
  DemoSampleStock,
  DemoStatus,
  ErrorResponse,
  HealthResponse,
  MarketBreadth,
  MarketDataSource,
  MarketIndex,
  MarketOverview,
  MarketSector,
  MarketSectors,
  MarketSignals,
  MarketTurnover,
  PaginatedResponse,
  PaginationMeta,
  PaginationRequest,
  Response,
  SectorLeader,
  SignalParameters,
  SignalResult,
} from './generated'
