// 本文件只转出由后端 OpenAPI 生成的 wire types，不维护第二份手写 DTO。
export type {
  ApiPaths,
  DemoCounts,
  DemoSampleStock,
  DemoStatus,
  ErrorResponse,
  HealthResponse,
  MarketBreadth,
  MarketDataSource,
  MarketIndex,
  MarketOverview,
  MarketRanking,
  MarketRankings,
  MarketSector,
  MarketSectors,
  MarketSignals,
  MarketTurnover,
  PaginatedResponse,
  PaginationMeta,
  PaginationRequest,
  Response,
  SectorLeader,
  SignalParameters,
  SignalResult,
  StockMetric,
  StockMetrics,
  StockBar,
  StockBars,
  StockBenchmark,
  StockBenchmarkPoint,
  StockEffectiveRange,
  StockOverview,
  StockQuote,
  StockSparkline,
  StockSparklinePoint,
} from './generated'
